print("================================")
print("      GERENCIADOR DE TAREFAS")
print("================================")
print("")
print("1 - Adicionar tarefa")
print("2 - Listar tarefas")
print("3 - Concluir tarefa")
print("4 - Excluir tarefa")
print("0 - Sair")